# Generated by Django 5.2.13 on 2026-08-10 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('households', '0003_reconcile_membership_uniqueness'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotentOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('response_body', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idempotent_operations', to='api.devicesession')),
            ],
        ),
        migrations.CreateModel(
            name='SyncChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField(blank=True, null=True)),
                ('entity_type', models.CharField(max_length=32)),
                ('entity_uuid', models.UUIDField()),
                ('entity_version', models.PositiveBigIntegerField()),
                ('operation', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=8)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sync_changes', to='api.devicesession')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_changes', to='households.household')),
            ],
        ),
        migrations.AddConstraint(
            model_name='idempotentoperation',
            constraint=models.UniqueConstraint(fields=('device_session', 'operation_id'), name='unique_idempotent_operation_per_device'),
        ),
        migrations.AddIndex(
            model_name='syncchange',
            index=models.Index(fields=['household', 'id'], name='sync_syncch_househo_0da156_idx'),
        ),
        migrations.AddIndex(
            model_name='syncchange',
            index=models.Index(fields=['household', 'entity_type', 'entity_uuid'], name='sync_syncch_househo_316337_idx'),
        ),
    ]
