# Generated by Django 5.2.13 on 2026-08-10 14:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0003_reconcile_membership_uniqueness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('windows', 'Windows'), ('ios', 'iOS'), ('android', 'Android')], max_length=16)),
                ('name', models.CharField(max_length=80)),
                ('access_token_digest', models.CharField(max_length=64, unique=True)),
                ('access_expires_at', models.DateTimeField()),
                ('refresh_token_digest', models.CharField(max_length=64, unique=True)),
                ('refresh_expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_sessions', to='households.financialowner')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_sessions', to='households.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsedRefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('used_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_refresh_tokens', to='api.devicesession')),
            ],
        ),
    ]
