# Generated by Django 5.2.13 on 2026-08-19 02:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_account_sync_metadata'),
        ('categories', '0005_category_sync_metadata'),
        ('households', '0003_reconcile_membership_uniqueness'),
        ('transactions', '0005_transaction_sync_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome da Conta / Compromisso')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor Base (R$)')),
                ('due_day', models.PositiveSmallIntegerField(help_text='Dia do mês em que esta conta costuma vencer (1 a 31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia do Vencimento')),
                ('type', models.CharField(choices=[('expense', 'Despesa'), ('income', 'Receita')], default='expense', max_length=10, verbose_name='Tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_bills', to='categories.category', verbose_name='Categoria')),
                ('default_account', models.ForeignKey(blank=True, help_text='Conta bancária sugerida para débito', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_bills', to='accounts.account', verbose_name='Conta Bancária Padrão')),
                ('financial_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_bills', to='households.financialowner')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_bills', to='households.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta Fixa / Recorrente',
                'verbose_name_plural': 'Contas Fixas & Recorrentes',
                'ordering': ['due_day', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BillInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField()),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor do Mês (R$)')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Paga'), ('skipped', 'Ignorada')], default='pending', max_length=15, verbose_name='Status')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_bill_instances', to='accounts.account', verbose_name='Conta Debitada')),
                ('financial_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_instances', to='households.financialowner')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_instances', to='households.household')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_instance', to='transactions.transaction', verbose_name='Transação Vinculada')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='bills.recurringbill')),
            ],
            options={
                'verbose_name': 'Instância Mensal de Conta',
                'verbose_name_plural': 'Instâncias Mensais de Contas',
                'ordering': ['due_date', 'bill__name'],
                'unique_together': {('bill', 'month', 'year')},
            },
        ),
    ]
