# Generated by Django 5.2.13 on 2026-08-13 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0005_account_sync_metadata'),
        ('api', '0001_initial'),
        ('households', '0003_reconcile_membership_uniqueness'),
        ('transactions', '0005_transaction_sync_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('provider', models.CharField(max_length=32)),
                ('product_type', models.CharField(max_length=32)),
                ('file_sha256', models.CharField(max_length=64)),
                ('statement_start', models.DateField()),
                ('statement_end', models.DateField()),
                ('expires_at', models.DateTimeField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('preview_ready', 'Preview ready'),
                            ('needs_account_link', 'Needs account link'),
                            ('completed', 'Completed'),
                            ('failed', 'Failed'),
                            ('cancelled', 'Cancelled'),
                        ],
                        default='preview_ready',
                        max_length=32,
                    ),
                ),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                (
                    'account',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='import_batches',
                        to='accounts.account',
                    ),
                ),
                (
                    'device_session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='import_batches',
                        to='api.devicesession',
                    ),
                ),
                (
                    'financial_owner',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='import_batches',
                        to='households.financialowner',
                    ),
                ),
                (
                    'household',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='import_batches',
                        to='households.household',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ImportRecord',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('line_number', models.PositiveIntegerField()),
                (
                    'external_id',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ('posted_on', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(max_length=10)),
                ('fingerprint', models.CharField(max_length=64)),
                (
                    'outcome',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('duplicate', 'Duplicate'),
                            ('warning', 'Warning'),
                            ('created', 'Created'),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    'batch',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='records',
                        to='imports.importbatch',
                    ),
                ),
                (
                    'transaction',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='import_records',
                        to='transactions.transaction',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='SourceReference',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('provider', models.CharField(max_length=32)),
                ('external_id', models.CharField(max_length=255)),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='source_references',
                        to='accounts.account',
                    ),
                ),
                (
                    'transaction',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='source_references',
                        to='transactions.transaction',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ImportAccountLink',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('provider', models.CharField(max_length=32)),
                ('product_type', models.CharField(max_length=32)),
                ('external_account_id', models.CharField(max_length=255)),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='import_account_links',
                        to='accounts.account',
                    ),
                ),
                (
                    'household',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='import_account_links',
                        to='households.household',
                    ),
                ),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(
                        fields=(
                            'household',
                            'provider',
                            'product_type',
                            'external_account_id',
                        ),
                        name='unique_import_account_link',
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(
                fields=['household', 'status', 'expires_at'],
                name='imports_imp_househo_3a367a_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='importrecord',
            index=models.Index(
                fields=['batch', 'line_number'], name='imports_imp_batch_i_caae3d_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='sourcereference',
            index=models.Index(
                fields=['account', 'provider', 'external_id'],
                name='imports_sou_account_0e2d72_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='sourcereference',
            constraint=models.UniqueConstraint(
                fields=('account', 'provider', 'external_id'),
                name='unique_source_reference_external_id',
            ),
        ),
    ]
