# Generated by Django 5.2.13 on 2026-08-13

import uuid
from importlib import import_module

from django.db import migrations, models

boundary_migration = import_module(
    'imports.migrations.0002_enforce_household_boundaries'
)


def _populate_batch_uuids(apps, schema_editor):
    batch_model = apps.get_model('imports', 'ImportBatch')
    for batch in batch_model.objects.filter(uuid__isnull=True).iterator():
        batch.uuid = uuid.uuid4()
        batch.save(update_fields=['uuid'])


class Migration(migrations.Migration):
    dependencies = [('imports', '0002_enforce_household_boundaries')]

    operations = [
        migrations.RunSQL(
            boundary_migration.DROP_TRIGGERS,
            boundary_migration.CREATE_TRIGGERS,
        ),
        migrations.AddField(
            model_name='importbatch',
            name='external_account_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importbatch',
            name='is_repeated_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(
            _populate_batch_uuids,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunSQL(
            boundary_migration.CREATE_TRIGGERS,
            boundary_migration.DROP_TRIGGERS,
        ),
    ]
