# Generated by Django 5.2.13 on 2026-08-15

import uuid
from importlib import import_module

from django.db import migrations, models

boundary_migration = import_module(
    'imports.migrations.0002_enforce_household_boundaries'
)

BACKFILL_CHUNK = 500


def _populate_record_uuids(apps, schema_editor):
    record_model = apps.get_model('imports', 'ImportRecord')
    pending = record_model.objects.filter(uuid__isnull=True).order_by('pk')
    last_pk = 0
    while True:
        chunk = list(pending.filter(pk__gt=last_pk)[:BACKFILL_CHUNK])
        if not chunk:
            return
        for record in chunk:
            record.uuid = uuid.uuid4()
        record_model.objects.bulk_update(chunk, ['uuid'])
        last_pk = chunk[-1].pk


class Migration(migrations.Migration):
    dependencies = [('imports', '0003_import_batch_preview_metadata')]

    operations = [
        migrations.RunSQL(
            boundary_migration.DROP_TRIGGERS,
            boundary_migration.CREATE_TRIGGERS,
        ),
        migrations.AddField(
            model_name='importrecord',
            name='uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(
            _populate_record_uuids,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='importrecord',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunSQL(
            boundary_migration.CREATE_TRIGGERS,
            boundary_migration.DROP_TRIGGERS,
        ),
    ]
