# Generated by Django 5.2.13 on 2026-08-18 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_sync_metadata'),
        ('imports', '0004_import_record_uuid'),
        ('transactions', '0005_transaction_sync_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importaccountlink',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_account_links', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='sourcereference',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_references', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='sourcereference',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_references', to='transactions.transaction'),
        ),
    ]
