# Generated by Django 5.2.13 on 2026-08-10 14:59

import uuid

from django.db import migrations, models


BATCH_SIZE = 500


def backfill_account_uuids(apps, schema_editor):
    Account = apps.get_model('accounts', 'Account')
    database_alias = schema_editor.connection.alias
    last_pk = 0
    while True:
        rows = list(
            Account.objects.using(database_alias)
            .filter(pk__gt=last_pk)
            .order_by('pk')[:BATCH_SIZE]
        )
        if not rows:
            break
        for row in rows:
            row.uuid = uuid.uuid4()
        Account.objects.using(database_alias).bulk_update(
            rows,
            ['uuid'],
            batch_size=BATCH_SIZE,
        )
        last_pk = rows[-1].pk


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_protect_legacy_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='uuid',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(
            backfill_account_uuids,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='account',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name='account',
            name='sync_version',
            field=models.PositiveBigIntegerField(default=1, editable=False),
        ),
    ]
