"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    fallback = 'True' if default else 'False'
    return os.environ.get(name, fallback).strip().lower() in {'1', 'true', 'yes', 'on'}


SECRET_KEY = os.environ['SECRET_KEY']

DEBUG = env_bool('DEBUG')

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('ALLOWED_HOSTS', '*').split(',')
    if host.strip()
] or ['*']

SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', default=not DEBUG)
SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', default=not DEBUG)
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', default=not DEBUG)
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS')
SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD')
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'

if env_bool('TRUST_PROXY_HEADERS'):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_TRUSTED_ORIGINS = [
    origin
    for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'core',
    'households',
    'accounts',
    'categories',
    'profiles',
    'transactions',
    'users',
    'ai',
    'imports',
    'api',
    'sync.apps.SyncConfig',
    'bills',
    'cards',
]

MIDDLEWARE = [
    'api.middleware.RequestIdMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'api.middleware.ApiObservabilityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': False,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

SQLITE_PATH = os.environ.get('SQLITE_PATH')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': Path(SQLITE_PATH) if SQLITE_PATH else BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator'
        ),
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.authentication.DeviceTokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'api.pagination.ApiCursorPagination',
    'PAGE_SIZE': 50,
    'EXCEPTION_HANDLER': 'api.exceptions.api_exception_handler',
    'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer'],
    'DEFAULT_THROTTLE_RATES': {
        'login': '5/minute',
        'refresh': '30/minute',
    },
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'skip_api_request_logs': {
            '()': 'api.logging.SkipApiRequestLogFilter',
        },
    },
    'formatters': {
        'api_json': {
            '()': 'api.logging.JsonFormatter',
        },
        'safe_django_json': {
            '()': 'api.logging.SafeDjangoFormatter',
        },
        'api_diagnostic_json': {
            '()': 'api.logging.DiagnosticJsonFormatter',
        },
    },
    'handlers': {
        'api_stdout': {
            'class': 'logging.StreamHandler',
            'formatter': 'api_json',
            'stream': 'ext://sys.stdout',
        },
        'api_diagnostic_stdout': {
            'class': 'logging.StreamHandler',
            'formatter': 'api_diagnostic_json',
            'stream': 'ext://sys.stdout',
        },
        'null': {
            'class': 'logging.NullHandler',
        },
        'safe_django_stdout': {
            'class': 'logging.StreamHandler',
            'formatter': 'safe_django_json',
            'stream': 'ext://sys.stdout',
        },
        'safe_django_request_stdout': {
            'class': 'logging.StreamHandler',
            'filters': ['skip_api_request_logs'],
            'formatter': 'safe_django_json',
            'stream': 'ext://sys.stdout',
        },
    },
    'loggers': {
        'lar_finance.api': {
            'handlers': ['api_stdout'],
            'level': 'INFO',
            'propagate': False,
        },
        'lar_finance.api.diagnostic': {
            'handlers': ['api_diagnostic_stdout'],
            'level': 'ERROR',
            'propagate': False,
        },
        'lar_finance.backup': {
            'handlers': ['api_stdout'],
            'level': 'INFO',
            'propagate': False,
        },
        'lar_finance.deploy': {
            'handlers': ['api_stdout'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['safe_django_stdout'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['safe_django_request_stdout'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['null'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['safe_django_stdout'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.security.DisallowedHost': {
            'handlers': ['safe_django_stdout'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
