# Generated by Django 5.2.13 on 2026-08-10 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0002_backfill_existing_financial_data'),
        ('transactions', '0002_transaction_household_financial_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='financial_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='households.financialowner'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='households.household'),
        ),
    ]
