# Generated by Django 5.2.13 on 2026-08-10 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def abort_reverse_if_legacy_uniqueness_conflicts(apps, schema_editor):
    Category = apps.get_model('categories', 'Category')
    database_alias = schema_editor.connection.alias
    conflict_count = (
        Category.objects.using(database_alias)
        .values('user_id', 'name', 'type')
        .annotate(category_count=models.Count('pk'))
        .filter(category_count__gt=1)
        .count()
    )
    if conflict_count:
        raise RuntimeError(
            'category 0003 reverse preflight failed: '
            f'incompatible_legacy_unique_groups={conflict_count}'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_household'),
        ('households', '0002_backfill_existing_financial_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='category',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='households.household'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('household', 'name', 'type'), name='unique_category_per_household_name_type'),
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            abort_reverse_if_legacy_uniqueness_conflicts,
        ),
    ]
