# Generated by Django 5.2.13 on 2026-08-19 21:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_category_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='teto mensal (R$)'),
        ),
    ]
