import 'package:flutter/material.dart';

import 'lar_tokens.g.dart';

abstract final class LarColors {
  static const darkCanvas = LarGeneratedColors.darkCanvas,
      darkSurface = LarGeneratedColors.darkSurface,
      darkElevated = LarGeneratedDarkColors.surfaceElevated,
      lightCanvas = LarGeneratedColors.lightCanvas,
      lightSurface = LarGeneratedColors.lightSurface,
      lightElevated = LarGeneratedLightColors.surfaceElevated,
      champagne = LarGeneratedColors.champagne,
      champagneSelectedDark = LarGeneratedColors.champagneSelectedDark,
      champagneSelectedLight = LarGeneratedColors.champagneSelectedLight,
      mineral = LarGeneratedColors.mineral,
      mineralOnDark = LarGeneratedColors.mineralOnDark,
      amber = LarGeneratedColors.amber,
      danger = LarGeneratedColors.danger,
      darkDanger = LarGeneratedDarkColors.stateDanger,
      lightDanger = LarGeneratedLightColors.stateDanger,
      darkText = LarGeneratedColors.darkText,
      darkTextSecondary = LarGeneratedDarkColors.textSecondary,
      darkTextMuted = LarGeneratedDarkColors.textMuted,
      lightText = LarGeneratedColors.lightText,
      lightTextSecondary = LarGeneratedLightColors.textSecondary,
      lightTextMuted = LarGeneratedLightColors.textMuted,
      darkBorder = LarGeneratedDarkColors.borderDefault,
      lightBorder = LarGeneratedLightColors.borderDefault,
      darkOutline = LarGeneratedDarkColors.borderStrong,
      lightOutline = LarGeneratedLightColors.borderStrong,
      darkShadow = LarGeneratedDarkColors.shadowColor,
      lightShadow = LarGeneratedLightColors.shadowColor;
  static const all = <Color>[
    darkCanvas,
    darkSurface,
    darkElevated,
    lightCanvas,
    lightSurface,
    lightElevated,
    champagne,
    champagneSelectedDark,
    champagneSelectedLight,
    mineral,
    mineralOnDark,
    amber,
    danger,
    darkDanger,
    lightDanger,
    darkText,
    darkTextSecondary,
    darkTextMuted,
    lightText,
    lightTextSecondary,
    lightTextMuted,
    darkBorder,
    lightBorder,
    darkOutline,
    lightOutline,
  ];
}
