# Generated by Django 5.2.13 on 2026-08-19 19:42

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0005_account_sync_metadata'),
        ('categories', '0005_category_sync_metadata'),
        ('households', '0003_reconcile_membership_uniqueness'),
        ('transactions', '0005_transaction_sync_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=120, verbose_name='Nome do Cartão'),
                ),
                (
                    'limit',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal('0.01'))
                        ],
                        verbose_name='Limite Total (R$)',
                    ),
                ),
                (
                    'closing_day',
                    models.PositiveSmallIntegerField(
                        help_text='Dia do mês em que a fatura fecha (1 a 31)',
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name='Dia do Fechamento',
                    ),
                ),
                (
                    'due_day',
                    models.PositiveSmallIntegerField(
                        help_text='Dia do mês em que a fatura vence (1 a 31)',
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name='Dia do Vencimento',
                    ),
                ),
                (
                    'color',
                    models.CharField(
                        default='#2F756A', max_length=20, verbose_name='Cor (Hex)'
                    ),
                ),
                (
                    'brand',
                    models.CharField(
                        choices=[
                            ('visa', 'Visa'),
                            ('mastercard', 'Mastercard'),
                            ('elo', 'Elo'),
                            ('amex', 'American Express'),
                            ('hipercard', 'Hipercard'),
                            ('other', 'Outro'),
                        ],
                        default='visa',
                        max_length=30,
                        verbose_name='Bandeira',
                    ),
                ),
                (
                    'last_digits',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=4,
                        verbose_name='Últimos 4 Dígitos',
                    ),
                ),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'financial_owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='credit_cards',
                        to='households.financialowner',
                    ),
                ),
                (
                    'household',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='credit_cards',
                        to='households.household',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='credit_cards',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'cartão de crédito',
                'verbose_name_plural': 'cartões de crédito',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CreditCardInvoice',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'month',
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name='Mês de Referência',
                    ),
                ),
                (
                    'year',
                    models.PositiveSmallIntegerField(verbose_name='Ano de Referência'),
                ),
                ('closing_date', models.DateField(verbose_name='Data de Fechamento')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('open', 'Aberta'),
                            ('closed', 'Fechada'),
                            ('paid', 'Paga'),
                            ('overdue', 'Atrasada'),
                        ],
                        default='open',
                        max_length=15,
                        verbose_name='Status',
                    ),
                ),
                (
                    'paid_amount',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        max_digits=12,
                        verbose_name='Valor Pago (R$)',
                    ),
                ),
                (
                    'paid_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='Pago em'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'credit_card',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='invoices',
                        to='cards.creditcard',
                    ),
                ),
                (
                    'household',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='credit_card_invoices',
                        to='households.household',
                    ),
                ),
                (
                    'payment_account',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='card_invoice_payments',
                        to='accounts.account',
                        verbose_name='Conta de Débito',
                    ),
                ),
                (
                    'payment_transaction',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='card_invoice',
                        to='transactions.transaction',
                        verbose_name='Transação Financeira de Pagamento',
                    ),
                ),
            ],
            options={
                'verbose_name': 'fatura de cartão',
                'verbose_name_plural': 'faturas de cartão',
                'ordering': ['-year', '-month'],
                'unique_together': {('credit_card', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='CreditCardExpense',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'description',
                    models.CharField(max_length=200, verbose_name='Descrição'),
                ),
                (
                    'amount',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal('0.01'))
                        ],
                        verbose_name='Valor da Parcela (R$)',
                    ),
                ),
                ('date', models.DateField(verbose_name='Data da Compra')),
                (
                    'installments_count',
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(48),
                        ],
                        verbose_name='Total de Parcelas',
                    ),
                ),
                (
                    'installment_number',
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(48),
                        ],
                        verbose_name='Número da Parcela',
                    ),
                ),
                (
                    'installment_group_id',
                    models.UUIDField(db_index=True, default=uuid.uuid4),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='credit_card_expenses',
                        to='categories.category',
                        verbose_name='Categoria',
                    ),
                ),
                (
                    'credit_card',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='expenses',
                        to='cards.creditcard',
                    ),
                ),
                (
                    'financial_owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='credit_card_expenses',
                        to='households.financialowner',
                    ),
                ),
                (
                    'household',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='credit_card_expenses',
                        to='households.household',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='credit_card_expenses',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'invoice',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='expenses',
                        to='cards.creditcardinvoice',
                    ),
                ),
            ],
            options={
                'verbose_name': 'despesa no cartão',
                'verbose_name_plural': 'despesas no cartão',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
