# Generated by Django 5.2.13 on 2026-08-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardexpense',
            name='external_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name='ID Externo (FITID)',
            ),
        ),
    ]
